### ISSUE TITLE
Bug: "all goroutines are asleep - deadlock" 

### ISSUE THREAD

**Issue by Somewheref** [ADimoska/SOMASExtended#81] opened 2024-12-02 12:58 UTC
Currently the threshold is only applied at the end of iteration (3 turns per iteration). In the final outcome, I believe we will extend turn number to like 20, and apply threshold every once a while (say 3).

While trying to do the above, the "fatal error: all goroutines are asleep - deadlock!" appears at the end of iteration, at the cs.teamMutex.Lock() line.

I tried removing it, but it will cause some nil pointer reference.

To reproduce, see my data playback branch: #54 

![image](https://github.com/user-attachments/assets/a4d57104-04a1-460c-8a38-56b647385238)

**Comment by arnavxkohli** [comment] 2024-12-02 17:54
@Somewheref, the issue is because of the `defer cs.teamsMutex.Unlock()` statement, this defers the release of the lock on the teams data structure until after the `RunTurn()` function completes its execution. I think I have a fix, but there is another bug I am running into, for some reason, the team being returned for the `teamID` is `nil` for certain agents, when trying to kill them

**Comment by arnavxkohli** [comment] 2024-12-02 18:05
Fixed completely (except the occasional nil pointer de-reference which should be fixed when @vedantvasugupta 's changes are patched in).

**Closed** 2024-12-03 11:27 UTC
Labels: bug, pending review
